dist: bionic
jobs:
  include:
  - name: Kong CE 2.3.2
    env: KONG_VERSION=2.3.2
install:
- git clone --single-branch https://github.com/Kong/kong-pongo ../kong-pongo
- "../kong-pongo/pongo.sh up"
- "../kong-pongo/pongo.sh build"
script:
- "../kong-pongo/pongo.sh lint"
- "../kong-pongo/pongo.sh run"
deploy:
  - provider: script
    skip_cleanup: true
    script: luarocks upload kong-plugin-url-rewrite-*.rockspec --api-key=$LUAROCKS_API_KEY
    on:
      branch: main
notifications:
  slack:
    secure: jdpsVClaE5jWO+qDcclHNMZgzyxtrDFQrmANOELvetU6QjbP2ehC9n/U7HrV72WAo6rdml0bQlRvQGPOUF1eqUaB0OBIc1r8WH3Ea/1a/KHVmqS8Q2hFfk61BYG9Hx7mb+lmI3BjvRJoQ4kCkVIi/6rjkRFkYPHid/qsU28NX8RFQQTtqFIMhFL060DMMOJgSQgS4q1E5JwNYXtgdPPweBTGqeAfDhiNDa0kgouLelAwhmuIB0RReMEYCGiy6DEK1dn8m78DRmO4St7Dp/m578DRBRN0nhvNPHfNWDr2zqFlc4cOTz20PZvbB/kRreKu35EwCiUVcwIvu0HSHJkhQMLgjvnrdP3sf8sGh0eUV7eWIqGrAYXcNsIMsUkf/N/hadY3hTovnyg2zlfMtmIDIL+pHbxzrnwn0cGncGJOD2etYytkgbErXwB97Y8lecdnj9lkCusR9SICTQkGnTUVkvd98J6tPpdxje+F/LYaEzBj0R0W/2kuTSV4f5ONmkM3fxDpd2UOW8/U8qtALTyW+yDLyAtXpXnzISRqgt21kD/BhAbk0nFNTvWY4wrXoIOIsWk7ypBLn5V3Ofdfn8w5U7To4fuAd8wAbO55As4Yxs/56bYpjapHCDhr7jHSaMTKu9RkVHnBWgSqgy2b2REdEKsJtrJLRv+wo8klN27NAa8=
